# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

publish-docker:
  stage: deploy
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - tags

publish-pypi:
    image: python:3.8.3-buster
    stage: deploy
    script:
        - pip install poetry
        - poetry build
        - poetry publish
    only:
    - tags
